version: "3"
services:
  family-chronicles-server:
    container_name: family-chronicles-server
    image: family-chronicles/family-chronicles-server
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    networks:
      - family-chronicles-network
    depends_on:
      - mongo
      - mongo-express
      - mysql
      - phpmyadmin

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
      - type: volume
        source: MONGO_LOG
        target: /var/log/mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: family-chronicles
    networks:
      - family-chronicles-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_URL: mongodb://0.0.0.0:27017
    networks:
      - family-chronicles-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: family-chronicles
      MYSQL_USER: family-chronicles
      MYSQL_PASSWORD: family-chronicles

    networks:
      - family-chronicles-network
    volumes:
      - ./mysql:/var/lib/mysql
    depends_on:
      - mongo
      - mongo-express

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:lastest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: family-chronicles
      PMA_PASSWORD: family-chronicles
    networks:
      - family-chronicles-network
    depends_on:
      - mysql

networks:
  family-chronicles-network:
    driver: bridge
    name: family-chronicles-network

volumes:
  MONGO_DATA:
  MONGO_CONFIG:
  MONGO_LOG:
